clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S accumulate_default.cpp -o accumulate_default_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S accumulate_custom.cpp -o accumulate_custom_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S all_of.cpp -o all_of_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S any_of.cpp -o any_of_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S copy.cpp -o copy_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S copy_if.cpp -o copy_if_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S count.cpp -o count_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S count_if.cpp -o count_if_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S fill.cpp -o fill_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S find.cpp -o find_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S find_if.cpp -o find_if_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S is_sorted.cpp -o is_sorted_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S none_of.cpp -o none_of_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S remove.cpp -o remove_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S remove_if.cpp -o remove_if_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S replace.cpp -o replace_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S replace_if.cpp -o replace_if_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S reverse.cpp -o reverse_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S transform_abs.cpp -o transform_abs_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S transform_inc.cpp -o transform_inc_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S transform_neg.cpp -o transform_neg_avx2.s
clang++ -Rpass=loop-vectorize -Rpass-missed=loop-vectorize -O3 -mavx2 -S unique.cpp -o unique_avx2.s
